import Head from "next/head";
import React from "react";
import Navbar from "./Navbar";

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>GreenGift</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/Green-gift-favicon.png" />
      </Head>
      <main>
        <div>
          <div>
            <Navbar />
          </div>
          {children}
        </div>
      </main>
    </>
  );
};

export default Layout;
