import Head from "next/head";
import React from "react";
import Navbar from "./Navbar";

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>GreenGift</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/Green-gift-favicon.png" />
      </Head>
      <main>
        {/* <div> */}
        {/* <div className="w-1/6">
            <Sidebar />
          </div> */}
        <div className="">
          <div>
            <Navbar />
          </div>
          {children}
        </div>
        {/* </div> */}

        {/* <div className="w-1/6"></div> */}
        {/* </div> */}
      </main>
    </>
  );
};

export default Layout;
